spring:
  application:
    name: kama-notes
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000
    jedis:
      pool:
        enabled: on
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kama.notes.entity.custom
  type-handlers-package: com.kama.notes.typehandler

jwt:
  secret: abc123
  expiration: 2592000

server:
  port: 8080
