spring:
  application:
    name: kama-notes
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kamanote_tech?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  profiles:
    active: dev
  redis:
    host: localhost
    password: 123456
    port: 6380
    database: 0
    timeout: 2000
    jedis:
      pool:
        enabled: on
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 2000
  mail:
    host: smtp.qq.com
    port: 465
    username: your@qq.com
    password: your
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtps
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kama.notes.entity.custom
  type-handlers-package: com.kama.notes.typehandler

jwt:
  secret: abc123
  expiration: 2592000

server:
  port: 8080

# 自定义邮件配置
mail:
  verify-code:
    expire-minutes: 15
    resend-interval: 60
    template-path: "templates/mail/verify-code.html"

upload:
  path: upload/directory # 请替换为实际的上传路径
  url-prefix: http://localhost:8080/upload # 请替换为实际的URL前缀


debug: true
